class HairstyleData {
  static const Map<String, String> maleHairstyles = {
    'BuzzCut': 'assets/hair_styles/man/1.png',
    'UnderCut': 'assets/hair_styles/man/2.png',
    'Pompadour': 'assets/hair_styles/man/3.png',
    'SlickBack': 'assets/hair_styles/man/4.png',
    'CurlyShag': 'assets/hair_styles/man/5.png',
    'WavyShag': 'assets/hair_styles/man/6.png',
    'FauxHawk': 'assets/hair_styles/man/7.png',
    'Spiky': 'assets/hair_styles/man/8.png',
    'CombOver': 'assets/hair_styles/man/9.png',
    'HighTightFade': 'assets/hair_styles/man/10.png',
    'ManBun': 'assets/hair_styles/man/11.png',
    'Afro': 'assets/hair_styles/man/12.png',
    'LowFade': 'assets/hair_styles/man/13.png',
    'UndercutLongHair': 'assets/hair_styles/man/14.png',
    'TwoBlockHaircut': 'assets/hair_styles/man/15.png',
    'TexturedFringe': 'assets/hair_styles/man/16.png',
    'BluntBowlCut': 'assets/hair_styles/man/17.png',
    'LongWavyCurtainBangs': 'assets/hair_styles/man/18.png',
    'MessyTousled': 'assets/hair_styles/man/19.png',
    'CornrowBraids': 'assets/hair_styles/man/20.png',
    'LongHairTiedUp': 'assets/hair_styles/man/21.png',
    'Middle-parted': 'assets/hair_styles/man/22.png',
  };

  static const Map<String, String> femaleHairstyles = {
    'ShortPixieWithShavedSides': 'assets/hair_styles/woman/1.png',
    'ShortNeatBob': 'assets/hair_styles/woman/2.png',
    'DoubleBun': 'assets/hair_styles/woman/3.png',
    'Updo': 'assets/hair_styles/woman/4.png',
    'Spiked': 'assets/hair_styles/woman/5.png',
    'bowlCut': 'assets/hair_styles/woman/6.png',
    'Chignon': 'assets/hair_styles/woman/7.png',
    'PixieCut': 'assets/hair_styles/woman/8.png',
    'SlickedBack': 'assets/hair_styles/woman/9.png',
    'LongCurly': 'assets/hair_styles/woman/10.png',
    'CurlyBob': 'assets/hair_styles/woman/11.png',
    'StackedCurlsInShortBob': 'assets/hair_styles/woman/12.png',
    'SidePartCombOverHairstyleWithHighFade': 'assets/hair_styles/woman/13.png',
    'WavyFrenchBobVibesfrom1920': 'assets/hair_styles/woman/14.png',
    'BobCut': 'assets/hair_styles/woman/15.png',
    'ShortTwintails': 'assets/hair_styles/woman/16.png',
    'ShortCurlyPixie': 'assets/hair_styles/woman/17.png',
    'LongStraight': 'assets/hair_styles/woman/18.png',
    'LongWavy': 'assets/hair_styles/woman/19.png',
    'FishtailBraid': 'assets/hair_styles/woman/20.png',
    'TwinBraids': 'assets/hair_styles/woman/21.png',
    'Ponytail': 'assets/hair_styles/woman/22.png',
    'Dreadlocks': 'assets/hair_styles/woman/23.png',
    'Cornrows': 'assets/hair_styles/woman/24.png',
    'ShoulderLengthHair': 'assets/hair_styles/woman/25.png',
    'LooseCurlyAfro': 'assets/hair_styles/woman/26.png',
    'LongTwintails': 'assets/hair_styles/woman/27.png',
    'LongHimeCut': 'assets/hair_styles/woman/28.png',
  };

  static const Map<String, String> hairColors = {
    'blonde': 'assets/hair_styles/hair_color/blonde.png',
    'platinumBlonde': 'assets/hair_styles/hair_color/platinumBlonde.png',
    'brown': 'assets/hair_styles/hair_color/brown.png',
    'lightBrown': 'assets/hair_styles/hair_color/lightBrown.png',
    'blue': 'assets/hair_styles/hair_color/blue.png',
    'lightBlue': 'assets/hair_styles/hair_color/lightBlue.png',
    'purple': 'assets/hair_styles/hair_color/purple.png',
    'lightPurple': 'assets/hair_styles/hair_color/lightPurple.png',
    'pink': 'assets/hair_styles/hair_color/pink.png',
    'black': 'assets/hair_styles/hair_color/black.png',
    'white': 'assets/hair_styles/hair_color/white.png',
    'grey': 'assets/hair_styles/hair_color/grey.png',
    'silver': 'assets/hair_styles/hair_color/silver.png',
    'red': 'assets/hair_styles/hair_color/red.png',
    'orange': 'assets/hair_styles/hair_color/orange.png',
    'green': 'assets/hair_styles/hair_color/green.png',
    'gradient': 'assets/hair_styles/hair_color/gradient.png',
    'multicolored': 'assets/hair_styles/hair_color/multicolored.png',
    'darkBlue': 'assets/hair_styles/hair_color/darkBlue.png',
    'burgundy': 'assets/hair_styles/hair_color/burgundy.png',
    'darkGreen': 'assets/hair_styles/hair_color/darkGreen.png',
  };
}
